### ISSUE TITLE
Use `https` instead of `http`

### ISSUE THREAD

**Issue by Zulbukharov** [ShivamWho/new-weather-app-react#11]
There are `browser` issues blocking requests from `https` to `http`.

<img width="890" alt="Снимок экрана 2022-10-03 в 16 08 24" src="https://user-images.githubusercontent.com/25000090/193552821-fc578789-80e0-4719-9c16-c28e7723efe0.png">

<img width="1017" alt="Снимок экрана 2022-10-03 в 16 10 08" src="https://user-images.githubusercontent.com/25000090/193552905-69e8b394-bec8-40f4-b962-e8987dab31c7.png">

**Comment by ojninja16** [comment]
I would like to do it...please assign it to me
