### ISSUE TITLE
Unequal padding in the weather info-container 

### ISSUE THREAD

**Issue by RahulSharma4329** [ShivamWho/new-weather-app-react#18]
There is padding only in the left side of the card which does not looks uniform i want to contribute to the project and improve its UI.

Before adding padding the card looks like: 
![image](https://user-images.githubusercontent.com/74984914/193688377-18bfdc96-5226-4163-872b-e1f04fea27e7.png)

after adding padding it'll look like:
![image](https://user-images.githubusercontent.com/74984914/193688793-d47e51ad-4f73-4d6d-a423-458d9789bd70.png)

**Comment by Olixpin** [comment]
Can you assign this task to me so I can work on it?

**Comment by AshishRaikwar1290** [comment]
assign me this issue
