### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by alisamadiii** [ShivamWho/new-weather-app-react#19]
I want to add some animation for the website.

**Comment by ShivamWho** [comment]
sure go for it

**Comment by alisamadiii** [comment]
Sorry, Now I am busy, Will do it later if I found time

**Comment by Aayushi-Mittal** [comment]
Can I work on it if there is no problem?

**Comment by alisamadiii** [comment]
Sure @Aayushi-Mittal 
You can work on this issue.

**Comment by alisamadiii** [comment]
Thanks for that

**Comment by ShivamWho** [comment]
It's fine @AliReza1083 🙂
@Aayushi-Mittal I have assigned it to you
