### ISSUE TITLE
Add loading when fetch data

### ISSUE THREAD

**Issue by madfarizki** [ShivamWho/new-weather-app-react#20]
Hi @ShivamWho, I want to add a loading animation when fetching data, like the example below:

![loading](https://user-images.githubusercontent.com/54702541/193733920-771923f5-26e3-4798-82be-070a94ddd6b0.png)

If you agree, please assign to me.

**Comment by AshishRaikwar1290** [comment]
assign me this issue

**Comment by ShivamWho** [comment]
@AhmdFarzki go for it 😊

**Comment by madfarizki** [comment]
@ShivamWho please check my pull request #29
