### ISSUE TITLE
Ask for location on load

### ISSUE THREAD

**Issue by Keith-Web3** [ShivamWho/new-weather-app-react#42]
The site only asks for your current location after you search for a location. I feel the user experience could be improved by asking for the user for access to their location as soon as the page loads then loading the weather information for the user location.

**Comment by mitpancholi98** [comment]
Hi there, I would like to work this out ..

**Comment by ShivamWho** [comment]
@Keith-Web3 do u want to work on this or should i assign this to @mitpancholi98 ?

**Comment by Keith-Web3** [comment]
@ShivamWho let me work on it
