### ISSUE TITLE
Animation Based On Weather 

### ISSUE THREAD

**Issue by HridoyHazard** [ShivamWho/new-weather-app-react#50]
Animation Based On Weather Such As When The Weather In Particular Area Is Rainly Then It Will Be Rainly Effect And Goes Like This For Other Weather........

**Comment by HridoyHazard** [comment]
assign this task to me plz

**Comment by ShivamWho** [comment]
@HridoyHazard there is already an issue raised for this

**Comment by HridoyHazard** [comment]
hi i cloned this repo and run it but the search is not working. Tried many location but it not working. can you plz check what's wrong ??
![image](https://user-images.githubusercontent.com/71395891/194737588-a09a65c5-97a1-4e58-bdef-3c551b4d9b19.png)

**Comment by ShivamWho** [comment]
Read CONTRIBUTING.md first

**Comment by HridoyHazard** [comment]
i'm not contributing man. i'm just running the project from my local directory. it not working why?

**Comment by ShivamWho** [comment]
you have to create an API key and add it to the .env file as I showed in CONTRIBUTING.md

**Comment by HridoyHazard** [comment]
hi i've added the animation.can i make a pr ? while making pr do i need to remove the .env file ??

**Comment by ShivamWho** [comment]
yes you can make a PR 🙂 and the .env file is in .gitignore so it will not be pushed

**Comment by HridoyHazard** [comment]
than you

**Comment by HridoyHazard** [comment]
#54
here is the pr
