### ISSUE TITLE
Font colour according to the background image

### ISSUE THREAD

**Issue by ShivamWho** [ShivamWho/new-weather-app-react#52]
Font colour in the Title and other data displayed should be changed according to the background image (which varies according to the weather) same while in dark mode

**Comment by jsvigneshkanna** [comment]
Hi @ShivamWho ,
Can you give some more brief with some screenshot on what changes to be made. That would help!

**Comment by ShivamWho** [comment]
<img width="718" alt="Screenshot 2022-10-09 183222" src="https://user-images.githubusercontent.com/78149368/194758297-7c44fd43-1744-4e96-90df-c4820c00dce2.png">
The text colour does not match the current background

**Comment by RohitSaini7** [comment]
please assign this to me

**Comment by YashGadia** [comment]
@ShivamWho I can resolve this kind of issue. So can you assign this to me?

**Comment by ShivamWho** [comment]
@Rohit-Saini7 i have assigned this to you
