### ISSUE TITLE
Not able to deploy website on Netlify

### ISSUE THREAD

**Issue by ShivamWho** [ShivamWho/new-weather-app-react#6]
<img width="548" alt="Screenshot 2022-10-02 155006" src="https://user-images.githubusercontent.com/78149368/193449393-77bb9d2f-1a5e-4d08-8da3-873ec4826e1e.png">

**Comment by InsightCracker** [comment]
There're bugs in line line 34 and 99 of the root file. Fix it nd deploy again

**Comment by ShivamWho** [comment]
I tried to fix it but it does not work can you give it a try

**Comment by InsightCracker** [comment]
I'll try it once I charged my machine. ..
Give me till tomorrow morning 😌

**Comment by Zulbukharov** [comment]
Hello @ShivamWho, created `PR` with the fixes.
#9
